### ISSUE TITLE
[TASK-017] Set up Health Monitoring and Observability

### ISSUE THREAD

**Issue by sadiuysal** [sadiuysal/memvoice#143]
---
name: 📋 Task
about: Create a development task for MemVoice features
title: '[TASK-017] Set up Health Monitoring and Observability'
labels: ['type/task', 'status/todo', 'component/infrastructure', 'priority/medium', 'phase/1d']
assignees: ''
---

## 📋 Task Description
Set up comprehensive health monitoring and observability system for MemVoice infrastructure, including application metrics, performance monitoring, health checks, alerting, and dashboards to ensure system reliability and enable proactive issue resolution.

## 🎯 Objective
Create a robust monitoring infrastructure that provides real-time visibility into system health, performance metrics, and user experience, enabling rapid detection and resolution of issues before they impact users.

## ✅ Acceptance Criteria
- [ ] Application health checks and status endpoints
- [ ] Performance metrics collection and visualization
- [ ] Database and external service monitoring
- [ ] Real-time alerting for critical issues
- [ ] Comprehensive logging with structured format
- [ ] Monitoring dashboards for operations team
- [ ] SLA tracking and reporting
- [ ] Automated incident response workflows

## 🏗️ Technical Requirements
**Performance Monitoring**:
- [ ] API response time tracking (<2s average)
- [ ] Database query performance monitoring
- [ ] Memory and CPU usage tracking
- [ ] External service dependency monitoring

**Availability Monitoring**:
- [ ] Service uptime tracking (>99.5% target)
- [ ] Health check endpoints for all services
- [ ] Dependency health verification
- [ ] Automated failover detection

**Alerting Requirements**:
- [ ] Critical alerts within 1 minute of issue detection
- [ ] Escalation policies for unresolved incidents
- [ ] Integration with communication channels (Slack, email)
- [ ] Alert fatigue prevention with intelligent grouping

### Files to Create/Modify:
```
backend/
├── src/
│   ├── api/v1/
│   │   └── health.py               # Health check endpoints
│   ├── services/
│   │   ├── health_service.py       # Health check service
│   │   └── metrics_service.py      # Metrics collection service
│   ├── middleware/
│   │   └── metrics_middleware.py   # Request metrics middleware
│   └── monitoring/
│       ├── __init__.py
│       ├── prometheus.py           # Prometheus metrics setup
│       ├── alerts.py               # Alert definitions
│       └── dashboards.py           # Dashboard configurations

infrastructure/
├── monitoring/
│   ├── prometheus/
│   │   ├── prometheus.yml          # Prometheus configuration
│   │   └── alerts.yml              # Alert rules
│   ├── grafana/
│   │   ├── dashboards/             # Grafana dashboard configs
│   │   └── provisioning/           # Grafana provisioning
│   └── docker-compose.monitoring.yml

scripts/
├── monitoring/
│   ├── setup-monitoring.sh         # Monitoring stack setup
│   └── health-check.sh             # Manual health verification
```

### Key Components:
1. **Health Check Service** (`src/services/health_service.py`):
```python
from typing import Dict, Any, List
from datetime import datetime, timedelta
from src.core.database import get_database
from src.services.external_services import FirecrawlService, PineconeService, ZepService
import asyncio
import logging
import psutil
import time

logger = logging.getLogger(__name__)

class HealthService:
    def __init__(self):
        self.firecrawl = FirecrawlService()
        self.pinecone = PineconeService()
        self.zep = ZepService()
        self.start_time = datetime.utcnow()

    async def get_health_status(self) -> Dict[str, Any]:
        """Get comprehensive health status"""
        
        health_checks = await asyncio.gather(
            self._check_database(),
            self._check_external_services(),
            self._check_system_resources(),
            self._check_application_metrics(),
            return_exceptions=True
        )

        database_health, services_health, system_health, app_metrics = health_checks

        # Determine overall status
        overall_status = "healthy"
        if any(isinstance(check, Exception) for check in health_checks):
            overall_status = "unhealthy"
        elif any(check.get("status") == "degraded" for check in health_checks if isinstance(check, dict)):
            overall_status = "degraded"

        return {
            "status": overall_status,
            "timestamp": datetime.utcnow().isoformat(),
            "uptime": str(datetime.utcnow() - self.start_time),
            "version": "1.0.0",  # Get from environment
            "checks": {
                "database": database_health if not isinstance(database_health, Exception) else {"status": "unhealthy", "error": str(database_health)},
                "external_services": services_health if not isinstance(services_health, Exception) else {"status": "unhealthy", "error": str(services_health)},
                "system": system_health if not isinstance(system_health, Exception) else {"status": "unhealthy", "error": str(system_health)},
                "application": app_metrics if not isinstance(app_metrics, Exception) else {"status": "unhealthy", "error": str(app_metrics)}
            }
        }

    async def _check_database(self) -> Dict[str, Any]:
        """Check database connectivity and performance"""
        try:
            start_time = time.time()
            
            # Test database connection
            db = await get_database()
            await db.execute("SELECT 1")
            
            connection_time = (time.time() - start_time) * 1000  # ms
            
            # Check connection pool status
            pool_info = {
                "active_connections": db.pool.get_stats().get("active_connections", 0),
                "idle_connections": db.pool.get_stats().get("idle_connections", 0)
            }
            
            status = "healthy"
            if connection_time > 1000:  # >1s is concerning
                status = "degraded"
            
            return {
                "status": status,
                "connection_time_ms": round(connection_time, 2),
                "pool_info": pool_info,
                "last_check": datetime.utcnow().isoformat()
            }
            
        except Exception as e:
            logger.error(f"Database health check failed: {str(e)}")
            return {
                "status": "unhealthy",
                "error": str(e),
                "last_check": datetime.utcnow().isoformat()
            }

    async def _check_external_services(self) -> Dict[str, Any]:
        """Check external service connectivity"""
        services = {
            "firecrawl": self.firecrawl,
            "pinecone": self.pinecone,
            "zep": self.zep
        }
        
        service_status = {}
        overall_status = "healthy"
        
        for service_name, service in services.items():
            try:
                start_time = time.time()
                
                # Perform health check specific to each service
                if hasattr(service, 'health_check'):
                    await service.health_check()
                else:
                    # Generic connectivity test
                    await service.test_connection()
                
                response_time = (time.time() - start_time) * 1000
                
                service_status[service_name] = {
                    "status": "healthy" if response_time < 5000 else "degraded",
                    "response_time_ms": round(response_time, 2),
                    "last_check": datetime.utcnow().isoformat()
                }
                
                if response_time > 5000:
                    overall_status = "degraded"
                    
            except Exception as e:
                logger.error(f"{service_name} health check failed: {str(e)}")
                service_status[service_name] = {
                    "status": "unhealthy",
                    "error": str(e),
                    "last_check": datetime.utcnow().isoformat()
                }
                overall_status = "unhealthy"
        
        return {
            "status": overall_status,
            "services": service_status
        }

    async def _check_system_resources(self) -> Dict[str, Any]:
        """Check system resource usage"""
        try:
            # CPU usage
            cpu_percent = psutil.cpu_percent(interval=1)
            
            # Memory usage
            memory = psutil.virtual_memory()
            memory_percent = memory.percent
            
            # Disk usage
            disk = psutil.disk_usage('/')
            disk_percent = (disk.used / disk.total) * 100
            
            # Determine status based on thresholds
            status = "healthy"
            if cpu_percent > 80 or memory_percent > 85 or disk_percent > 90:
                status = "degraded"
            if cpu_percent > 95 or memory_percent > 95 or disk_percent > 95:
                status = "unhealthy"
            
            return {
                "status": status,
                "cpu_percent": round(cpu_percent, 2),
                "memory_percent": round(memory_percent, 2),
                "disk_percent": round(disk_percent, 2),
                "memory_available_gb": round(memory.available / (1024**3), 2),
                "disk_free_gb": round(disk.free / (1024**3), 2),
                "last_check": datetime.utcnow().isoformat()
            }
            
        except Exception as e:
            logger.error(f"System resource check failed: {str(e)}")
            return {
                "status": "unhealthy",
                "error": str(e),
                "last_check": datetime.utcnow().isoformat()
            }

    async def _check_application_metrics(self) -> Dict[str, Any]:
        """Check application-specific metrics"""
        try:
            # Get recent error rates
            error_rate = await self._get_error_rate()
            
            # Get average response time
            avg_response_time = await self._get_avg_response_time()
            
            # Get active user sessions
            active_sessions = await self._get_active_sessions()
            
            # Get job queue status
            queue_status = await self._get_queue_status()
            
            status = "healthy"
            if error_rate > 5 or avg_response_time > 2000:  # 5% error rate or >2s response
                status = "degraded"
            if error_rate > 10 or avg_response_time > 5000:  # 10% error rate or >5s response
                status = "unhealthy"
            
            return {
                "status": status,
                "error_rate_percent": round(error_rate, 2),
                "avg_response_time_ms": round(avg_response_time, 2),
                "active_sessions": active_sessions,
                "queue_status": queue_status,
                "last_check": datetime.utcnow().isoformat()
            }
            
        except Exception as e:
            logger.error(f"Application metrics check failed: {str(e)}")
            return {
                "status": "unhealthy",
                "error": str(e),
                "last_check": datetime.utcnow().isoformat()
            }

    async def _get_error_rate(self) -> float:
        """Calculate error rate from recent requests"""
        # Implementation would query metrics store or logs
        # For now, return mock data
        return 1.2  # 1.2% error rate

    async def _get_avg_response_time(self) -> float:
        """Get average response time from recent requests"""
        # Implementation would query metrics store
        # For now, return mock data
        return 850.5  # 850ms average

    async def _get_active_sessions(self) -> int:
        """Get count of active user sessions"""
        # Implementation would query session store
        # For now, return mock data
        return 42

    async def _get_queue_status(self) -> Dict[str, Any]:
        """Get job queue status"""
        # Implementation would query Celery/Redis
        # For now, return mock data
        return {
            "pending_jobs": 5,
            "active_jobs": 2,
            "failed_jobs": 1,
            "workers_active": 3
        }
```

2. **Metrics Middleware** (`src/middleware/metrics_middleware.py`):
```python
from fastapi import Request
from starlette.middleware.base import BaseHTTPMiddleware
from prometheus_client import Counter, Histogram, Gauge
import time

# Prometheus metrics
REQUEST_COUNT = Counter(
    'http_requests_total',
    'Total HTTP requests',
    ['method', 'endpoint', 'status_code']
)

REQUEST_DURATION = Histogram(
    'http_request_duration_seconds',
    'HTTP request duration in seconds',
    ['method', 'endpoint']
)

ACTIVE_REQUESTS = Gauge(
    'http_requests_active',
    'Number of active HTTP requests'
)

class MetricsMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        # Extract endpoint pattern
        endpoint = self._get_endpoint_pattern(request)
        method = request.method
        
        # Track active requests
        ACTIVE_REQUESTS.inc()
        
        start_time = time.time()
        
        try:
            response = await call_next(request)
            status_code = str(response.status_code)
            
        except Exception as e:
            status_code = "500"
            raise e
            
        finally:
            # Record metrics
            duration = time.time() - start_time
            
            REQUEST_COUNT.labels(
                method=method,
                endpoint=endpoint,
                status_code=status_code
            ).inc()
            
            REQUEST_DURATION.labels(
                method=method,
                endpoint=endpoint
            ).observe(duration)
            
            ACTIVE_REQUESTS.dec()
        
        return response
    
    def _get_endpoint_pattern(self, request: Request) -> str:
        """Extract endpoint pattern from request"""
        if hasattr(request, 'route') and request.route:
            return request.route.path
        return request.url.path
```

3. **Health Check Endpoints** (`src/api/v1/health.py`):
```python
from fastapi import APIRouter, Depends
from src.services.health_service import HealthService
from src.core.dependencies import get_health_service

router = APIRouter(prefix="/health", tags=["health"])

@router.get("/")
async def health_check(
    health_service: HealthService = Depends(get_health_service)
):
    """Basic health check endpoint"""
    return {"status": "healthy", "timestamp": datetime.utcnow().isoformat()}

@router.get("/detailed")
async def detailed_health_check(
    health_service: HealthService = Depends(get_health_service)
):
    """Detailed health check with all components"""
    return await health_service.get_health_status()

@router.get("/ready")
async def readiness_check(
    health_service: HealthService = Depends(get_health_service)
):
    """Kubernetes readiness probe endpoint"""
    health_status = await health_service.get_health_status()
    
    if health_status["status"] in ["healthy", "degraded"]:
        return {"status": "ready"}
    else:
        raise HTTPException(status_code=503, detail="Service not ready")

@router.get("/live")
async def liveness_check():
    """Kubernetes liveness probe endpoint"""
    return {"status": "alive"}
```

4. **Prometheus Configuration** (`infrastructure/monitoring/prometheus/prometheus.yml`):
```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'memvoice-api'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'memvoice-health'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/health/detailed'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
```

5. **Alert Rules** (`infrastructure/monitoring/prometheus/alerts.yml`):
```yaml
groups:
  - name: memvoice-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status_code=~"5.."}[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds"

      - alert: DatabaseConnectionFailure
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection failure"
          description: "PostgreSQL database is not responding"

      - alert: HighCPUUsage
        expr: cpu_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      - alert: HighMemoryUsage
        expr: memory_percent > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%"

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} service is not responding"
```

## 🧪 Testing Requirements
- [ ] **Unit Tests** - Health check service methods
- [ ] **Integration Tests** - Monitoring stack integration
- [ ] **Load Tests** - Metrics collection under load
- [ ] **Chaos Tests** - Alert triggering during failures

### Test Cases:
```python
# Health service tests
@pytest.mark.asyncio
async def test_health_service_database_check():
    """Test database health check"""
    health_service = HealthService()
    
    result = await health_service._check_database()
    
    assert result["status"] in ["healthy", "degraded", "unhealthy"]
    assert "connection_time_ms" in result
    assert "last_check" in result

@pytest.mark.asyncio
async def test_health_service_external_services():
    """Test external services health check"""
    health_service = HealthService()
    
    result = await health_service._check_external_services()
    
    assert result["status"] in ["healthy", "degraded", "unhealthy"]
    assert "services" in result
    assert "firecrawl" in result["services"]

@pytest.mark.asyncio
async def test_health_endpoint_returns_status():
    """Test health endpoint returns proper status"""
    response = await client.get("/health/")
    
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"
```

## 🔗 Related Issues
- **Epic**: #127 - Phase 1: Core Foundation Infrastructure
- **Depends on**: #142 - Implement Comprehensive Error Handling
- **Related**: #144 - Create Testing Suite with Coverage
- **Blocks**: Production deployment readiness

## 🏷️ Component
- [x] **Infrastructure** (Monitoring) - Prometheus, Grafana, AlertManager
- [x] **Backend API** (FastAPI) - Health endpoints and metrics
- [x] **DevOps** (Docker) - Monitoring stack deployment

## 📊 Effort Estimate
- [x] **Medium** (2-3 days)
  - Day 1: Health check service and endpoints
  - Day 2: Metrics collection and Prometheus setup
  - Day 3: Grafana dashboards and alerting configuration

## 📚 Implementation Notes
**Key Considerations**:
- Implement comprehensive health checks for all dependencies
- Set up meaningful alerts that reduce false positives
- Create actionable dashboards for operations team
- Ensure monitoring doesn't impact application performance
- Plan for monitoring data retention and storage

**Technical Specifications**:
- **Prometheus**: Metrics collection and storage
- **Grafana**: Visualization and dashboards
- **AlertManager**: Alert routing and notification
- **Health Checks**: Kubernetes-compatible endpoints

**Performance Optimization**:
- Efficient metrics collection with minimal overhead
- Appropriate scrape intervals for different metrics
- Data retention policies for long-term storage
- Alert aggregation to prevent notification spam

## ⚠️ Risks & Dependencies
**Technical Risks**:
- Monitoring overhead impacting application performance
- Alert fatigue from too many notifications
- Monitoring system becoming single point of failure
- Storage requirements for metrics data

**Dependencies**:
- All application components for comprehensive monitoring
- Infrastructure for monitoring stack deployment
- External service APIs for dependency monitoring
- Communication channels for alert notifications

**Mitigation Strategies**:
- Implement efficient metrics collection
- Tune alert thresholds to reduce false positives
- Set up monitoring for the monitoring system itself
- Plan for metrics data archival and cleanup

## 🔍 Additional Context
**Monitoring Stack Components**:
- **Prometheus** - Metrics collection and storage
- **Grafana** - Visualization and dashboards
- **AlertManager** - Alert routing and notifications
- **Node Exporter** - System metrics collection
- **Postgres Exporter** - Database metrics
- **Redis Exporter** - Cache metrics

**Key Metrics to Track**:
- **Application**: Request rate, response time, error rate
- **System**: CPU, memory, disk usage
- **Database**: Connection pool, query performance
- **External Services**: Response time, availability
- **Business**: User registrations, content processing

**Alert Severity Levels**:
- **Critical** - Immediate attention required (service down)
- **Warning** - Attention needed soon (high resource usage)
- **Info** - Informational alerts (deployment notifications)

**Dashboard Categories**:
- **Overview** - High-level system health
- **Application** - API performance and errors
- **Infrastructure** - System resources and dependencies
- **Business** - User activity and feature usage
